/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSessionIdRouteImport } from './routes/s.$sessionId'
import { Route as SSessionIdRRunIdRouteImport } from './routes/s.$sessionId_.r.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSessionIdRoute = SSessionIdRouteImport.update({
  id: '/s/$sessionId',
  path: '/s/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SSessionIdRRunIdRoute = SSessionIdRRunIdRouteImport.update({
  id: '/s/$sessionId_/r/$runId',
  path: '/s/$sessionId/r/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s/$sessionId': typeof SSessionIdRoute
  '/s/$sessionId/r/$runId': typeof SSessionIdRRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s/$sessionId': typeof SSessionIdRoute
  '/s/$sessionId/r/$runId': typeof SSessionIdRRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/s/$sessionId': typeof SSessionIdRoute
  '/s/$sessionId_/r/$runId': typeof SSessionIdRRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/s/$sessionId' | '/s/$sessionId/r/$runId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/s/$sessionId' | '/s/$sessionId/r/$runId'
  id: '__root__' | '/' | '/s/$sessionId' | '/s/$sessionId_/r/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SSessionIdRoute: typeof SSessionIdRoute
  SSessionIdRRunIdRoute: typeof SSessionIdRRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$sessionId': {
      id: '/s/$sessionId'
      path: '/s/$sessionId'
      fullPath: '/s/$sessionId'
      preLoaderRoute: typeof SSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$sessionId_/r/$runId': {
      id: '/s/$sessionId_/r/$runId'
      path: '/s/$sessionId/r/$runId'
      fullPath: '/s/$sessionId/r/$runId'
      preLoaderRoute: typeof SSessionIdRRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SSessionIdRoute: SSessionIdRoute,
  SSessionIdRRunIdRoute: SSessionIdRRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
